import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./providers/ThemeProvider";
import TopNavbar from "./components/TopNavbar";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
    title: "Cake Shop",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang='en' className='light overflow-x-hidden overflow-auto'>
            <body className={montserrat.className}>
                <TopNavbar />
                <ThemeProvider>{children}</ThemeProvider>
            </body>
        </html>
    );
}
