import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Cake Shop",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang='en' className='light'>
            <body className={inter.className}>
                <ThemeProvider>{children}</ThemeProvider>
            </body>
        </html>
    );
}
